apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-169876214
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-169876214
    app.kubernetes.io/part-of: test-app-169876214
  name: java-quarkus-169876214
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-169876214
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-169876214
    spec:
      containers:
      - image: quay.io/hacdev/xtczsaa9-tenant/test-app-169876214/java-quarkus-169876214@sha256:2ac63b358c3531003c8954dcd072786934698b460893123454bafd9754ab2e11
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
