apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-169876214
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-169876214
    app.kubernetes.io/part-of: test-app-169876214
  name: java-quarkus-169876214ar2t
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: java-quarkus-169876214
    weight: null
status: {}
